config/routes.rb
Rails.application.routes.draw do
  root "cars#index"

  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord

  include Visible

  validates :chave, presence: true, length: { minimum: 10 }
  validates :modelo, presence: true, length: { minimum: 10 }
  validates :marca, presence: true, length: { minimum: 10 }
  validates :ano_modelo, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    byebug
    @cars = Car.all
  end

  def show 
    byebug
    @car = Car.find(params[:id])
  end

  def new 
    byebug
    @car = Car.new
  end
    
  def creat
    byebug
  @car = Car.new(car_params)
    if @car.save
      redirect_to @car
    else
      render :new, :unprocessable_entity
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])

    if @car.update(car_params)
      redirect_to @car
    else
      render :edit, status: :unprocessable_entity
    end  
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def car_params
    params.require(:car).permit(:chave, :modelo, :marca, :ano, :ano_modelo, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/cars/_form.html.erb
<%= form_with model: car do |form| %>
  <div>
    <%= form.label :chave %><br>
    <%= form.text_field :chave %>
    <% @car.errors.full_messages_for(:chave).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :marca %><br>
    <%= form.text_field :marca %>
    <% @car.errors.full_messages_for(:marca).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :modelo %><br>
    <%= form.text_field :modelo %>
    <% @car.errors.full_messages_for(:modelo).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :ano %><br>
    <%= form.text_field :ano %>
    <% @car.errors.full_messages_for(:ano).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :ano_modelo %><br>
    <%= form.text_field :ano_modelo %>
    <% @car.errors.full_messages_for(:ano_modelo).each do |message| %>
    <div><%= message %></div>
    <% end %>  
  </div>

 <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", car: @car %>

app/views/cars/index.html.erb
<h1>Car</h1>


<ul>
  <% @cars.each do |car| %>
  <% unless car.archived? %>
    <li>
      <%= link_to car.chave, car %>
      <%= link_to car.modelo, car %>
      <%= link_to car.ano, car %>
      <%= link_to car.ano_modelo, car %>
    </li>
  <% end %>
<% end %>  
</ul>

<%= link_to "New car", new_car_path %>

app/views/cars/new.html.erb
<h1>New Article</h1>

<%= render "form", car: @car %>

app/views/cars/show.html.erb
<h1><%= @car.chave %></h1>
<h1><%= @car.marca %></h1>
<h1><%= @car.modelo %></h1>
<h1><%= @car.ano %></h1>
<h1><%= @car.ano_modelo%></h1>


<ul>
  <li><%= link_to "Edit", edit_car_path(@car) %></li>
  <li><%= link_to "Destroy", car_path(@car), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>